### PR TITLE
Added failing test

### PR DESCRIPTION
**Pull request by xenmayer**
Now I'm trying to resolve this issue.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
`l` (lower L) does not belongs to compatible formats: http://php.net/manual/en/datetime.formats.date.php

**Comment by xenmayer** [comment]
@kylekatarnls ok, but problem not in lower `L`. problem in `M`. 
May month key equal for short and long date type `F` `M` in translations files.
PHP array gives last of two same items with same key. You can check ru translate file for example.

**Comment by xenmayer** [comment]
@kylekatarnls 

https://github.com/jenssegers/date/blob/233085153e5f334acd64b851b58d20dcf530aa0c/src/Lang/ru.php#L30

https://github.com/jenssegers/date/blob/233085153e5f334acd64b851b58d20dcf530aa0c/src/Lang/ru.php#L43

**Comment by kylekatarnls** [comment]
Input format is English-only as far as I know.

**Comment by xenmayer** [comment]
@kylekatarnls of course) library not working as expected with some languages, especially where used plural month names

**Comment by xenmayer** [comment]
now I think about month translation keys refactoring

**Pull request closed without merging**
