### PR TITLE
Moved self-update to before_install

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Though, I'd actually prefer it to just be removed.

### CODE REVIEW

**Comment by jenssegers** [comment]
Is it better to place them both under before_install like https://github.com/thephpleague/skeleton/blob/master/.travis.yml?

**Comment by GrahamCampbell** [comment]
No. That skeleton is out of date anyway.

**Comment by GrahamCampbell** [comment]
See how they have `script` instead of `install` there.

**Comment by GrahamCampbell** [comment]
https://github.com/thephpleague/factory-muffin/blob/master/.travis.yml

**Comment by jenssegers** [comment]
Do you know if they are planning to update the skeleton? Or are they abandoning it?

**Comment by GrahamCampbell** [comment]
Nobody has time I guess. Like, I'll update my own packages on there, but not other people's. I assume most of the other guys do the same.

**Pull request merged**
