### PR TITLE
Properly extend function `DiffForHumans`

### PR DESCRIPTION
**Pull request by armycoder**

### CODE REVIEW

**Comment by ackerchez** [comment]
pls do this quicky!

**Comment by mbardelmeijer** [comment]
@jenssegers could you take a look and this and possibly press 'merge' 😄

**Comment by kylekatarnls** [comment]
@ackerchez, @mbardelmeijer, you can just use the 1.22.1 version of Carbon in your dependencies until it's merged, it's not so urgent.

And this PR is a good quick fix, but it will add a $parts argument that has no effect, that's why I would recommend as a finest approach to align diffForHumans (something like jessengers before-changes, parent::diffForHumans(1, 2, 3, 4), after-changes and return).

**Comment by armycoder** [comment]
@kylekatarnls It is the proper way to extend something. Not just a quick fix. But right now nobody can use the function.

**Comment by DojoGeekRA** [comment]
@armycoder i totally agree with @kylekatarnls, there is no hurry for this fix, just lock your `nesbot/carbon` to the `1.22.1` and now **everybody** can use the function.

Adding a parameter to the method definition just for the sake of it, it's just awful. Developers will think that they will obtain the same behavior for the `$parts` parameter as they will with the Carbon library and in reality they will not (therefore creating a wave of Github issue requests).

**Comment by nonoesp** [comment]
Locking `nesbot/carbon` to the `1.22.1` worked for me — thanks!

**Comment by armycoder** [comment]
Well maybe a notice could be put up or something. I personally just added the argument in my vendor folder

**Comment by armycoder** [comment]
Well maybe a notice could be put up or something. I personally just added the argument in my vendor folder

**Comment by nonoesp** [comment]
@armycoder that worked for me too. (It's just that if this package is updated you'll introduce the bug once again.)

**Comment by kylekatarnls** [comment]
@nonoesp it have been in a way that is better IMHO. You better should upgrade jenssegers/date to ~3.3.1

**Pull request closed without merging**
