### PR TITLE
Fix hun lang file and test

### PR DESCRIPTION
**Pull request by balping**

### CODE REVIEW

**Comment by jenssegers** [comment]
Can you not revert the code style changes please?

**Comment by balping** [comment]
What do you mean? It has passed StyleCI. But sure, if you tell me what's wrong, I'll revert it

**Comment by jenssegers** [comment]
The array changes and the `diffForHumans`

**Comment by GrahamCampbell** [comment]
Just because it passed StyleCI, it doesn't mean you didn't make unrelated changes. It's possible that StyleCI isn't configured to normalize everything on this repo.

**Comment by GrahamCampbell** [comment]
As you can see:

image

It's not setup to normalize the array style either way.

**Comment by balping** [comment]
Done

**Comment by GrahamCampbell** [comment]
@jenssegers I'd recommend you enable the long array syntax fixer. ;)

**Comment by jenssegers** [comment]
@GrahamCampbell Yeah I'll make sure to add it to all my repos ;)

**Pull request merged**
