### PR TITLE
Event of locale update now handled correctly

### PR DESCRIPTION
**Pull request by SCIF**
Replaces #251 as it looks abandoned.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
It seems Laravel 5.4.36 also use `https://github.com/jenssegers/date/pull/295#issuecomment-400395585` so I recommend #295 instead.

**Comment by SCIF** [comment]
Heh, Taylor is terrible :( Closing this PR.

**Comment by kylekatarnls** [comment]
Commit found: https://github.com/laravel/framework/commit/3385fdc0f8e4890ab57261755bcbbf79f9ec828d
So, to be precise the class exists since 5.4.0 and the event name changed from `'locale.changed'` at the exact same commit. So a `>=5.4.0` check would do the trick, but the `class_exists` will not breaks if the class disappear in a next version.

**Comment by SCIF** [comment]
@kylekatarnls , not working library (throwing exception) is better than pretending working.

**Comment by kylekatarnls** [comment]
Not so black-or-/white situation. The auto-update of the locale is a minor feature comparing to all other features. If I am working on a 100% English-speaking application. It would really bother me to get prevented to update to Laravel 5.8 because of a feature I do not use is not yet compatible.

But if you just see some texts displayed in English instead of locale languages, it's a non-blocking problem even for the end user, and you see something is wrong with language synchronization and can decide to downgrade or not.

**Comment by kylekatarnls** [comment]
Woops, very bad example ^^

About testing, it's another problem, all features should be tested. For Carbon I mocked the Laravel objects in the locale unit tests: https://github.com/briannesbitt/Carbon/blob/master/tests/Laravel/ServiceProviderTest.php

Then recently I made a project to install real versions of Laravel and Carbon, then test the actual compatibility: https://github.com/kylekatarnls/carbon-laravel

It will run daily and one of the version is dev-master (so always the very last in-progress version)

This ways if tomorrow, the locale synchronization change in Laravel, it will raise an error (mail, slack, etc.) but meanwhile we adapt our code, the users will not be blocked.

**Comment by SCIF** [comment]
Totally agree, it's possible to test service provider. I've tested SP of my package as well, but particular this package is not covered so it's a weak side and implicit/shutted up fail could be hidden out of sight for a long time.

**Pull request closed without merging**
