### PR TITLE
Added Serbian language (latin script)

### PR DESCRIPTION
**Pull request by goksiii**
Added support for a latin script for the Serbian language.

### CODE REVIEW

**Comment by jenssegers** [comment]
The filename change might break existing installations though. What are the official language codes for both of these?

**Comment by goksiii** [comment]
For the filename, I have used RFC 5646 (https://tools.ietf.org/html/rfc5646) document. I built filenames for both of these with standardization that is defined in mentioned document. Official language codes for both of these is "sr", by ISO 639-1. In ISO 639-2 document, the language code for the Serbian language may have 2 or 3 characters, "sr" or "srp". 
I may add a latin version of Serbian language in this format "srp_Latin". What do you mean about this?

**Comment by goksiii** [comment]
Or I may use "sr_Latin" for the filename for a latin script version of the Serbian language. The filename for Cyrillic script version will stay same.

**Comment by goksiii** [comment]
@jenssegers any information about merging this pull request? are you ok with changes that I made on PR?  I need the latin script of Serbian language in my project.

**Comment by jenssegers** [comment]
This page mentions some other possibilities: http://www.lingoes.net/en/translator/langcode.htm

    sr-BA	Serbian (Latin) (Bosnia and Herzegovina)
    sr-BA	Serbian (Cyrillic) (Bosnia and Herzegovina)
    sr-SP	Serbian (Latin) (Serbia and Montenegro)
    sr-SP	Serbian (Cyrillic) (Serbia and Montenegro)

Any chance we could use one of these?

**Comment by goksiii** [comment]
@jenssegers 
Yes.
Filename of a Cyrillic script will stay same (only "sr.php"), but filename of a Latin script will be "sr-SP.php".

**Comment by goksiii** [comment]
@jenssegers PR is updated with changes. Can you review again this PR?

**Pull request merged**
