### PR TITLE
Bind Laravel LocaleUpdated event

### PR DESCRIPTION
**Pull request by matthewnessworthy**
Similar to https://github.com/jenssegers/date/pull/251/files but without requiring the version check

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, I don't think avoiding checking version worth listening 2 events, it means one more `$this->listeners[$event][] = $this->makeListener($listener);` executed, so 1 callback copy stored, and 1 more item to filter from the array (hash-mapped internally) when the event is triggered. It's very few storage and execution time used, but it still seems to me like unneeded when you can simply do a simple check once for all.

What do you think of it?

**Comment by matthewnessworthy** [comment]
@kylekatarnls In general I prefer to avoid version checking.
What about the following instead?
```
$localeChangedEvent = 'locale.changed';
// Laravel 5.6+ @see https://github.com/laravel/framework/commit/3385fdc0f8e4890ab57261755bcbbf79f9ec828d#diff-7b18a52eceff5eb716c1de268e98d55dR1045
if (class_exists('\\Illuminate\\Foundation\\Events\\LocaleUpdated')) {
	$localeChangedEvent = \Illuminate\Foundation\Events\LocaleUpdated::class;
}

$this->app['events']->listen($localeChangedEvent, function () {
    $this->setLocale();
});
```

**Comment by kylekatarnls** [comment]
Laravel 5.4.36 also use `\\Illuminate\\Foundation\\Events\\LocaleUpdated` so this solution is definitely better.

**Comment by matthewnessworthy** [comment]
@kylekatarnls Please check again, I've updated based on your most recent feedback.

**Comment by kylekatarnls** [comment]
Just to confirm than event name and class existence are well synchronized: https://github.com/laravel/framework/commit/3385fdc0f8e4890ab57261755bcbbf79f9ec828d

**Comment by jenssegers** [comment]
Thanks guys!

**Pull request merged**
