### PR TITLE
Fix awkward Korean Translation

### PR DESCRIPTION
**Pull request by darron1217**
It's really simple PR :)

### CODE REVIEW

**Comment by kylekatarnls** [comment]
The Travis failure is due to second overlap between `Date::now()` and the next `Date::now()` and can be fix by merging #289

**Comment by jenssegers** [comment]
Would love to get some additional reviewers on this :)

**Comment by darron1217** [comment]
Oh.. that was my mistake
Sorry i'll fix it

**Comment by darron1217** [comment]
I created clean PR again #290

**Pull request closed without merging**
