### PR TITLE
Welsh language translation file

### PR DESCRIPTION
**Pull request by meigwilym**
Translations for the Welsh language (Cymraeg). I've tested this to the best of my ability and it works. Thanks!

### CODE REVIEW

**Comment by jenssegers** [comment]
Can you also add it to the readme?

**Comment by meigwilym** [comment]
I've added to the readme - so I make a new PR with all files or just for the new Readme?

**Comment by meigwilym** [comment]
Thanks! I'm really chuffed with this.

**Comment by jenssegers** [comment]
Will tag a new version when Travis is done processing the recent PR merges.

**Comment by jenssegers** [comment]
Could you verify the `ago` and `from_now` translations for me?

See: https://travis-ci.org/jenssegers/date/jobs/121404411

**Pull request merged**
